name: Publish releases to npm
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'Publish to npm'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
          token: ${{ secrets.GH_RELEASE_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "github-cd-bot@ems.press"
      - run: npm version ${{ github.event.release.tag_name }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
      - run: git push
